#Generated by VPC

NAME=gcsdk
TARGET_PLATFORM=linux64
TARGET_PLATFORM_EXT=_client
VPC_HOST=linux

SRCROOT=..
LINUX_MAKEFILE=1
USE_VALVE_BINDIR=0
# If no configuration is specified, "release" will be used.
CFG ?= release




















################################################################################
#
# CFG=debug
#
################################################################################

ifeq "$(CFG)" "debug"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := gcsdk_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DNO_STEAM=1 -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=gcsdk -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DPROTOBUF -DTF -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/decaloverdose/Projects/srcmodbase-source/gcsdk -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ../gcsdk/generated_proto ../thirdparty/protobuf/src ../thirdparty/protobuf/third_party/abseil-cpp/ ../gcsdk/steamextra .. ../public ../public/gcsdk ../thirdparty/JSON_parser . 
CONFTYPE=lib
OUTPUTFILE=../build/lib/linuxsteamrt64/gcsdk_client.a
GAMEOUTPUTFILE=

CPPFILES= \
    ../common/protobuf_helpers.cpp \
    generated_proto/gcsdk_gcmessages.pb.cc \
    stdafx.cpp \
    gcclient.cpp \
    gcconstants.cpp \
    gclogger.cpp \
    gcmsg.cpp \
    job.cpp \
    jobmgr.cpp \
    jobtime.cpp \
    messagelist.cpp \
    msgprotobuf.cpp \
    netpacket.cpp \
    netpacketpool.cpp \
    protobufsharedobject.cpp \
    sharedobject.cpp \
    sharedobjectcache.cpp \
    gcclient_sharedobjectcache.cpp \
    steamextra/misc.cpp \
    steamextra/rtime.cpp \
    ../common/steamid.cpp \
    steamextra/tier1/hashglobals.cpp \
    steamextra/tier1/tsmempool.cpp \
    steamextra/tier1/tsmultimempool.cpp \
    workthreadpool.cpp \
    webapi_response.cpp \
    ../thirdparty/JSON_parser/JSON_parser.c \
    generated_proto/gcsystemmsgs.pb.cc

unexport CPPFILES

LIBFILES =

unexport LIBFILES

LIBFILENAMES =

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS = \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES = \
    steammessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt \
    gcsdk_gcmessages.proto \
    gcsystemmsgs.proto

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS = \
    _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/steammessages_dot_proto.sh \
    _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsdk_gcmessages_dot_proto.sh \
    _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsystemmsgs_dot_proto.sh

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS = \
    generated_proto/steammessages.pb.cc \
    generated_proto/steammessages.pb.h \
    generated_proto/gcsdk_gcmessages.pb.cc \
    generated_proto/gcsdk_gcmessages.pb.h \
    generated_proto/gcsystemmsgs.pb.cc \
    generated_proto/gcsystemmsgs.pb.h

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/protobuf_helpers.P \
    $(OBJ_DIR)/gcsdk_gcmessages.pb.P \
    $(OBJ_DIR)/stdafx.P \
    $(OBJ_DIR)/gcclient.P \
    $(OBJ_DIR)/gcconstants.P \
    $(OBJ_DIR)/gclogger.P \
    $(OBJ_DIR)/gcmsg.P \
    $(OBJ_DIR)/job.P \
    $(OBJ_DIR)/jobmgr.P \
    $(OBJ_DIR)/jobtime.P \
    $(OBJ_DIR)/messagelist.P \
    $(OBJ_DIR)/msgprotobuf.P \
    $(OBJ_DIR)/netpacket.P \
    $(OBJ_DIR)/netpacketpool.P \
    $(OBJ_DIR)/protobufsharedobject.P \
    $(OBJ_DIR)/sharedobject.P \
    $(OBJ_DIR)/sharedobjectcache.P \
    $(OBJ_DIR)/gcclient_sharedobjectcache.P \
    $(OBJ_DIR)/misc.P \
    $(OBJ_DIR)/rtime.P \
    $(OBJ_DIR)/steamid.P \
    $(OBJ_DIR)/hashglobals.P \
    $(OBJ_DIR)/tsmempool.P \
    $(OBJ_DIR)/tsmultimempool.P \
    $(OBJ_DIR)/workthreadpool.P \
    $(OBJ_DIR)/webapi_response.P \
    $(OBJ_DIR)/JSON_parser.P \
    $(OBJ_DIR)/gcsystemmsgs.pb.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: gcsdk_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# Custom Build Tool "Running Protocol Buffer Compiler on steammessages.proto..." for file "steammessages.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto = \
    steammessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto

CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on steammessages.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/steammessages_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/steammessages_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto

OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto = \
    generated_proto/steammessages.pb.cc \
    generated_proto/steammessages.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool steammessages_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/steammessages_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/steammessages_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/steammessages_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for steammessages_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/steammessages_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/steammessages_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto))


#
# Custom Build Tool "Running Protocol Buffer Compiler on gcsdk_gcmessages.proto..." for file "gcsdk_gcmessages.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto = \
    gcsdk_gcmessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on gcsdk_gcmessages.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsdk_gcmessages_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsdk_gcmessages_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto

OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto = \
    generated_proto/gcsdk_gcmessages.pb.cc \
    generated_proto/gcsdk_gcmessages.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool gcsdk_gcmessages_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsdk_gcmessages_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsdk_gcmessages_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsdk_gcmessages_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for gcsdk_gcmessages_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsdk_gcmessages_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsdk_gcmessages_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto))


#
# Custom Build Tool "Running Protocol Buffer Compiler on gcsystemmsgs.proto..." for file "gcsystemmsgs.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto = \
    gcsystemmsgs.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on gcsystemmsgs.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsystemmsgs_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsystemmsgs_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto

OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto = \
    generated_proto/gcsystemmsgs.pb.cc \
    generated_proto/gcsystemmsgs.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool gcsystemmsgs_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsystemmsgs_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsystemmsgs_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Debug/custom_build_tools/gcsystemmsgs_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for gcsystemmsgs_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsystemmsgs_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsystemmsgs_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto))


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/protobuf_helpers.P)
include $(wildcard $(OBJ_DIR)/gcsdk_gcmessages.pb.P)
include $(wildcard $(OBJ_DIR)/stdafx.P)
include $(wildcard $(OBJ_DIR)/gcclient.P)
include $(wildcard $(OBJ_DIR)/gcconstants.P)
include $(wildcard $(OBJ_DIR)/gclogger.P)
include $(wildcard $(OBJ_DIR)/gcmsg.P)
include $(wildcard $(OBJ_DIR)/job.P)
include $(wildcard $(OBJ_DIR)/jobmgr.P)
include $(wildcard $(OBJ_DIR)/jobtime.P)
include $(wildcard $(OBJ_DIR)/messagelist.P)
include $(wildcard $(OBJ_DIR)/msgprotobuf.P)
include $(wildcard $(OBJ_DIR)/netpacket.P)
include $(wildcard $(OBJ_DIR)/netpacketpool.P)
include $(wildcard $(OBJ_DIR)/protobufsharedobject.P)
include $(wildcard $(OBJ_DIR)/sharedobject.P)
include $(wildcard $(OBJ_DIR)/sharedobjectcache.P)
include $(wildcard $(OBJ_DIR)/gcclient_sharedobjectcache.P)
include $(wildcard $(OBJ_DIR)/misc.P)
include $(wildcard $(OBJ_DIR)/rtime.P)
include $(wildcard $(OBJ_DIR)/steamid.P)
include $(wildcard $(OBJ_DIR)/hashglobals.P)
include $(wildcard $(OBJ_DIR)/tsmempool.P)
include $(wildcard $(OBJ_DIR)/tsmultimempool.P)
include $(wildcard $(OBJ_DIR)/workthreadpool.P)
include $(wildcard $(OBJ_DIR)/webapi_response.P)
include $(wildcard $(OBJ_DIR)/JSON_parser.P)
include $(wildcard $(OBJ_DIR)/gcsystemmsgs.pb.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/protobuf_helpers.o: ../common/protobuf_helpers.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/protobuf_helpers.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/protobuf_helpers.o

$(OBJ_DIR)/gcsdk_gcmessages.pb.o: generated_proto/gcsdk_gcmessages.pb.cc $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcsdk_gcmessages.pb.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcsdk_gcmessages.pb.o

$(OBJ_DIR)/stdafx.o: stdafx.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/stdafx.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/stdafx.o

$(OBJ_DIR)/gcclient.o: gcclient.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcclient.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcclient.o

$(OBJ_DIR)/gcconstants.o: gcconstants.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcconstants.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcconstants.o

$(OBJ_DIR)/gclogger.o: gclogger.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gclogger.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gclogger.o

$(OBJ_DIR)/gcmsg.o: gcmsg.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcmsg.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcmsg.o

$(OBJ_DIR)/job.o: job.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/job.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/job.o

$(OBJ_DIR)/jobmgr.o: jobmgr.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/jobmgr.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/jobmgr.o

$(OBJ_DIR)/jobtime.o: jobtime.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/jobtime.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/jobtime.o

$(OBJ_DIR)/messagelist.o: messagelist.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/messagelist.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/messagelist.o

$(OBJ_DIR)/msgprotobuf.o: msgprotobuf.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/msgprotobuf.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/msgprotobuf.o

$(OBJ_DIR)/netpacket.o: netpacket.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/netpacket.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/netpacket.o

$(OBJ_DIR)/netpacketpool.o: netpacketpool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/netpacketpool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/netpacketpool.o

$(OBJ_DIR)/protobufsharedobject.o: protobufsharedobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/protobufsharedobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/protobufsharedobject.o

$(OBJ_DIR)/sharedobject.o: sharedobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sharedobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sharedobject.o

$(OBJ_DIR)/sharedobjectcache.o: sharedobjectcache.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sharedobjectcache.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sharedobjectcache.o

$(OBJ_DIR)/gcclient_sharedobjectcache.o: gcclient_sharedobjectcache.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcclient_sharedobjectcache.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcclient_sharedobjectcache.o

$(OBJ_DIR)/misc.o: steamextra/misc.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/misc.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/misc.o

$(OBJ_DIR)/rtime.o: steamextra/rtime.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/rtime.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/rtime.o

$(OBJ_DIR)/steamid.o: ../common/steamid.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/steamid.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/steamid.o

$(OBJ_DIR)/hashglobals.o: steamextra/tier1/hashglobals.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/hashglobals.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/hashglobals.o

$(OBJ_DIR)/tsmempool.o: steamextra/tier1/tsmempool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/tsmempool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/tsmempool.o

$(OBJ_DIR)/tsmultimempool.o: steamextra/tier1/tsmultimempool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/tsmultimempool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/tsmultimempool.o

$(OBJ_DIR)/workthreadpool.o: workthreadpool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/workthreadpool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/workthreadpool.o

$(OBJ_DIR)/webapi_response.o: webapi_response.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/webapi_response.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/webapi_response.o

$(OBJ_DIR)/JSON_parser.o: ../thirdparty/JSON_parser/JSON_parser.c $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/JSON_parser.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/JSON_parser.o

$(OBJ_DIR)/gcsystemmsgs.pb.o: generated_proto/gcsystemmsgs.pb.cc $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcsystemmsgs.pb.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcsystemmsgs.pb.o

endif # (CFG=debug)




















################################################################################
#
# CFG=release
#
################################################################################

ifeq "$(CFG)" "release"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := gcsdk_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DNO_STEAM=1 -DNDEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=gcsdk -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DPROTOBUF -DTF -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/decaloverdose/Projects/srcmodbase-source/gcsdk -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ../gcsdk/generated_proto ../thirdparty/protobuf/src ../thirdparty/protobuf/third_party/abseil-cpp/ ../gcsdk/steamextra .. ../public ../public/gcsdk ../thirdparty/JSON_parser . 
CONFTYPE=lib
OUTPUTFILE=../build/lib/linuxsteamrt64/gcsdk_client.a
GAMEOUTPUTFILE=

CPPFILES= \
    ../common/protobuf_helpers.cpp \
    generated_proto/gcsdk_gcmessages.pb.cc \
    stdafx.cpp \
    ../common/debug_lib_check.cpp \
    gcclient.cpp \
    gcconstants.cpp \
    gclogger.cpp \
    gcmsg.cpp \
    job.cpp \
    jobmgr.cpp \
    jobtime.cpp \
    messagelist.cpp \
    msgprotobuf.cpp \
    netpacket.cpp \
    netpacketpool.cpp \
    protobufsharedobject.cpp \
    sharedobject.cpp \
    sharedobjectcache.cpp \
    gcclient_sharedobjectcache.cpp \
    steamextra/misc.cpp \
    steamextra/rtime.cpp \
    ../common/steamid.cpp \
    steamextra/tier1/hashglobals.cpp \
    steamextra/tier1/tsmempool.cpp \
    steamextra/tier1/tsmultimempool.cpp \
    workthreadpool.cpp \
    webapi_response.cpp \
    ../thirdparty/JSON_parser/JSON_parser.c \
    generated_proto/gcsystemmsgs.pb.cc

unexport CPPFILES

LIBFILES =

unexport LIBFILES

LIBFILENAMES =

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS = \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES = \
    steammessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt \
    gcsdk_gcmessages.proto \
    gcsystemmsgs.proto

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS = \
    _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/steammessages_dot_proto.sh \
    _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsdk_gcmessages_dot_proto.sh \
    _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsystemmsgs_dot_proto.sh

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS = \
    generated_proto/steammessages.pb.cc \
    generated_proto/steammessages.pb.h \
    generated_proto/gcsdk_gcmessages.pb.cc \
    generated_proto/gcsdk_gcmessages.pb.h \
    generated_proto/gcsystemmsgs.pb.cc \
    generated_proto/gcsystemmsgs.pb.h

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/protobuf_helpers.P \
    $(OBJ_DIR)/gcsdk_gcmessages.pb.P \
    $(OBJ_DIR)/stdafx.P \
    $(OBJ_DIR)/debug_lib_check.P \
    $(OBJ_DIR)/gcclient.P \
    $(OBJ_DIR)/gcconstants.P \
    $(OBJ_DIR)/gclogger.P \
    $(OBJ_DIR)/gcmsg.P \
    $(OBJ_DIR)/job.P \
    $(OBJ_DIR)/jobmgr.P \
    $(OBJ_DIR)/jobtime.P \
    $(OBJ_DIR)/messagelist.P \
    $(OBJ_DIR)/msgprotobuf.P \
    $(OBJ_DIR)/netpacket.P \
    $(OBJ_DIR)/netpacketpool.P \
    $(OBJ_DIR)/protobufsharedobject.P \
    $(OBJ_DIR)/sharedobject.P \
    $(OBJ_DIR)/sharedobjectcache.P \
    $(OBJ_DIR)/gcclient_sharedobjectcache.P \
    $(OBJ_DIR)/misc.P \
    $(OBJ_DIR)/rtime.P \
    $(OBJ_DIR)/steamid.P \
    $(OBJ_DIR)/hashglobals.P \
    $(OBJ_DIR)/tsmempool.P \
    $(OBJ_DIR)/tsmultimempool.P \
    $(OBJ_DIR)/workthreadpool.P \
    $(OBJ_DIR)/webapi_response.P \
    $(OBJ_DIR)/JSON_parser.P \
    $(OBJ_DIR)/gcsystemmsgs.pb.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: gcsdk_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# Custom Build Tool "Running Protocol Buffer Compiler on steammessages.proto..." for file "steammessages.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto = \
    steammessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto

CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on steammessages.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/steammessages_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/steammessages_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto

OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto = \
    generated_proto/steammessages.pb.cc \
    generated_proto/steammessages.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool steammessages_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/steammessages_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/steammessages_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/steammessages_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_steammessages_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/steammessages_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_steammessages_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for steammessages_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/steammessages_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/steammessages_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_steammessages_dot_proto))


#
# Custom Build Tool "Running Protocol Buffer Compiler on gcsdk_gcmessages.proto..." for file "gcsdk_gcmessages.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto = \
    gcsdk_gcmessages.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on gcsdk_gcmessages.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsdk_gcmessages_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsdk_gcmessages_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto

OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto = \
    generated_proto/gcsdk_gcmessages.pb.cc \
    generated_proto/gcsdk_gcmessages.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool gcsdk_gcmessages_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsdk_gcmessages_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsdk_gcmessages_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsdk_gcmessages_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsdk_gcmessages_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsdk_gcmessages_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for gcsdk_gcmessages_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsdk_gcmessages_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsdk_gcmessages_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_gcsdk_gcmessages_dot_proto))


#
# Custom Build Tool "Running Protocol Buffer Compiler on gcsystemmsgs.proto..." for file "gcsystemmsgs.proto"
#
DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto = \
    gcsystemmsgs.proto \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto = \
    { \
        $(ECHO) "Running Protocol Buffer Compiler on gcsystemmsgs.proto..." && \
        { $(SHELL) _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsystemmsgs_dot_proto.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsystemmsgs_dot_proto.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto

OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto = \
    generated_proto/gcsystemmsgs.pb.cc \
    generated_proto/gcsystemmsgs.pb.h

unexport OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool gcsystemmsgs_dot_proto start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsystemmsgs_dot_proto
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsystemmsgs_dot_proto

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/gcsystemmsgs_dot_proto $(OUTPUTS_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto): _vpc_/generated_scripts_gcsdk/linux64/Release/custom_build_tools/gcsystemmsgs_dot_proto.sh $(DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_gcsystemmsgs_dot_proto)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for gcsystemmsgs_dot_proto start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/gcsystemmsgs_dot_proto","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/gcsystemmsgs_dot_proto",$(call CUSTOM_BUILD_TOOL_ACTION_gcsystemmsgs_dot_proto))


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/protobuf_helpers.P)
include $(wildcard $(OBJ_DIR)/gcsdk_gcmessages.pb.P)
include $(wildcard $(OBJ_DIR)/stdafx.P)
include $(wildcard $(OBJ_DIR)/debug_lib_check.P)
include $(wildcard $(OBJ_DIR)/gcclient.P)
include $(wildcard $(OBJ_DIR)/gcconstants.P)
include $(wildcard $(OBJ_DIR)/gclogger.P)
include $(wildcard $(OBJ_DIR)/gcmsg.P)
include $(wildcard $(OBJ_DIR)/job.P)
include $(wildcard $(OBJ_DIR)/jobmgr.P)
include $(wildcard $(OBJ_DIR)/jobtime.P)
include $(wildcard $(OBJ_DIR)/messagelist.P)
include $(wildcard $(OBJ_DIR)/msgprotobuf.P)
include $(wildcard $(OBJ_DIR)/netpacket.P)
include $(wildcard $(OBJ_DIR)/netpacketpool.P)
include $(wildcard $(OBJ_DIR)/protobufsharedobject.P)
include $(wildcard $(OBJ_DIR)/sharedobject.P)
include $(wildcard $(OBJ_DIR)/sharedobjectcache.P)
include $(wildcard $(OBJ_DIR)/gcclient_sharedobjectcache.P)
include $(wildcard $(OBJ_DIR)/misc.P)
include $(wildcard $(OBJ_DIR)/rtime.P)
include $(wildcard $(OBJ_DIR)/steamid.P)
include $(wildcard $(OBJ_DIR)/hashglobals.P)
include $(wildcard $(OBJ_DIR)/tsmempool.P)
include $(wildcard $(OBJ_DIR)/tsmultimempool.P)
include $(wildcard $(OBJ_DIR)/workthreadpool.P)
include $(wildcard $(OBJ_DIR)/webapi_response.P)
include $(wildcard $(OBJ_DIR)/JSON_parser.P)
include $(wildcard $(OBJ_DIR)/gcsystemmsgs.pb.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/protobuf_helpers.o: ../common/protobuf_helpers.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/protobuf_helpers.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/protobuf_helpers.o

$(OBJ_DIR)/gcsdk_gcmessages.pb.o: generated_proto/gcsdk_gcmessages.pb.cc $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcsdk_gcmessages.pb.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcsdk_gcmessages.pb.o

$(OBJ_DIR)/stdafx.o: stdafx.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/stdafx.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/stdafx.o

$(OBJ_DIR)/debug_lib_check.o: ../common/debug_lib_check.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/debug_lib_check.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/debug_lib_check.o

$(OBJ_DIR)/gcclient.o: gcclient.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcclient.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcclient.o

$(OBJ_DIR)/gcconstants.o: gcconstants.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcconstants.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcconstants.o

$(OBJ_DIR)/gclogger.o: gclogger.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gclogger.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gclogger.o

$(OBJ_DIR)/gcmsg.o: gcmsg.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcmsg.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcmsg.o

$(OBJ_DIR)/job.o: job.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/job.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/job.o

$(OBJ_DIR)/jobmgr.o: jobmgr.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/jobmgr.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/jobmgr.o

$(OBJ_DIR)/jobtime.o: jobtime.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/jobtime.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/jobtime.o

$(OBJ_DIR)/messagelist.o: messagelist.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/messagelist.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/messagelist.o

$(OBJ_DIR)/msgprotobuf.o: msgprotobuf.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/msgprotobuf.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/msgprotobuf.o

$(OBJ_DIR)/netpacket.o: netpacket.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/netpacket.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/netpacket.o

$(OBJ_DIR)/netpacketpool.o: netpacketpool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/netpacketpool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/netpacketpool.o

$(OBJ_DIR)/protobufsharedobject.o: protobufsharedobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/protobufsharedobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/protobufsharedobject.o

$(OBJ_DIR)/sharedobject.o: sharedobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sharedobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sharedobject.o

$(OBJ_DIR)/sharedobjectcache.o: sharedobjectcache.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sharedobjectcache.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sharedobjectcache.o

$(OBJ_DIR)/gcclient_sharedobjectcache.o: gcclient_sharedobjectcache.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcclient_sharedobjectcache.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcclient_sharedobjectcache.o

$(OBJ_DIR)/misc.o: steamextra/misc.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/misc.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/misc.o

$(OBJ_DIR)/rtime.o: steamextra/rtime.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/rtime.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/rtime.o

$(OBJ_DIR)/steamid.o: ../common/steamid.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/steamid.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/steamid.o

$(OBJ_DIR)/hashglobals.o: steamextra/tier1/hashglobals.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/hashglobals.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/hashglobals.o

$(OBJ_DIR)/tsmempool.o: steamextra/tier1/tsmempool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/tsmempool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/tsmempool.o

$(OBJ_DIR)/tsmultimempool.o: steamextra/tier1/tsmultimempool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/tsmultimempool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/tsmultimempool.o

$(OBJ_DIR)/workthreadpool.o: workthreadpool.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/workthreadpool.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/workthreadpool.o

$(OBJ_DIR)/webapi_response.o: webapi_response.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/webapi_response.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/webapi_response.o

$(OBJ_DIR)/JSON_parser.o: ../thirdparty/JSON_parser/JSON_parser.c $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/JSON_parser.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/JSON_parser.o

$(OBJ_DIR)/gcsystemmsgs.pb.o: generated_proto/gcsystemmsgs.pb.cc $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/gcsystemmsgs.pb.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/gcsystemmsgs.pb.o

endif # (CFG=release)
